<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\ProductAlert\Block\Email\Stock */
?>
<tr style="padding:0 60px;display:block">
    <td class="product__alert__container"
        style="display:block;padding:30px 25px;border-radius:5px;border:1px solid #cad3a6">
        <?php if ($_products = $block->getProducts()) : ?>
        <table>
            <?php foreach ($_products as $_product) : ?>
                <tr>
                    <td class="col photo">
                        <?= $block->getImage($_product, 'product_thumbnail_image_stock_alert', ['class' => 'photo image'])->toHtml() ?>
                    </td>
                    <td class="col item">
                        <p style="margin-bottom: 5px;margin-left: 15px;">
                            <strong class="product name">
                                <?= $block->escapeHtml($_product->getName()) ?>
                            </strong>
                        </p>
                        <div style="margin-left: 15px;">
                            <table width="100%">
                                <tbody>
                                <tr>
                                    <td><?= $block->escapeHtml(__('Color: ')) ?></td>
                                    <td><?= $_condition = $_product->getAttributeText('color');
                                        $_coditionDefault = $_product->getResource()->getAttribute('color')->getFrontend()->getValue($_product); ?></td>
                                </tr>
                                <tr>
                                    <td><?= $block->escapeHtml(__('Size: ')) ?></td>
                                    <td><?= $_condition = $_product->getAttributeText('size');
                                        $_coditionDefault = $_product->getResource()->getAttribute('size')->getFrontend()->getValue($_product); ?></td>
                                </tr>
                                <tr>
                                    <td><?= $block->escapeHtml(__('SKU: ')) ?></td>
                                    <td><?= $_product->getSku(); ?></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </td>
</tr>
    <tr style="display:block;padding:20px 60px 0 60px">
        <td style="display:block"><a href="<?= $block->escapeUrl($block->getStore()->getBaseUrl()) ?>"
                                     style="font-size:16px;color:#fff;font-weight:600;display:block;margin:30px auto;max-width:235px;text-decoration:none;background:#82992f;text-align:center;height:53px;border-radius:3px;line-height:55px"><?= __('Go to Decowraps') ?></a>
        </td>
    </tr>
    <tr>
        <td style="text-align:center;">
            <a href="<?= $block->escapeUrl($block->getUnsubscribeUrl()) ?>"
               style="color:#8f8f8f;text-decoration:underline;font-size:12px;text-align:center;"><?= $block->escapeHtml(__('Unsubscribe from all stock alerts')) ?></a>
        </td>
    </tr>
<?php endif; ?>
