<?php

namespace Uzer\Checkoutstep\Block\Adminhtml\Sales\Orde\View;

use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Element\Template\Context;
use Magento\Sales\Api\Data\OrderInterface;
use Magento\Sales\Api\OrderRepositoryInterface;
use Magento\Sales\Model\Order;

class PurchaseOrder extends Template
{

    protected OrderRepositoryInterface $orderRepository;
    protected ?string $purchaseOrder = null;

    public function __construct(OrderRepositoryInterface $orderRepository, Context $context, array $data = [])
    {
        parent::__construct($context, $data);
        $this->orderRepository = $orderRepository;
    }


    protected function _beforeToHtml()
    {
        $orderId = $this->getRequest()->getParam('order_id');
        /** @var Order|OrderInterface $order */
        $order = $this->orderRepository->get($orderId);
        $this->purchaseOrder = $order->getData('purchase_order');
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string|null
     */
    public function getPurchaseOrder(): ?string
    {
        return $this->purchaseOrder;
    }


}
