<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Weee\Block\Item\Price\Renderer
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Weee\Helper\Data $weeeHelper */
$weeeHelper = $block->getData('weeeHelper');

$customFormat = \Magento\Framework\App\ObjectManager::getInstance()->create(\Uzer\Checkoutstep\Model\CustomFormat::class);

$item = $block->getItem();
?>
<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
<span class="price-including-tax" data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <span class="cart-tax-total"
                  data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= (int)$item->getId() ?>"}}'>
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
        <?= /* @noEscape */
        $customFormat->formatLong($block->getUnitDisplayPriceInclTax()) ?>
            </span>

        <?php if ($weeeHelper->getApplied($item)): ?>
            <span class="cart-tax-info no-display" id="unit-item-tax-details<?= (int)$item->getId() ?>">
                <?php foreach ($weeeHelper->getApplied($item) as $tax): ?>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                        <?= /* @noEscape */
                        $customFormat->formatLong($tax['amount_incl_tax']) ?>
                    </span>
                <?php endforeach; ?>
            </span>

            <?php if ($block->displayFinalPrice()): ?>
                <span class="cart-tax-total"
                      data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= (int)$item->getId() ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total Incl. Tax')) ?>">
                        <?= /* @noEscape */
                        $customFormat->formatLong($block->getFinalUnitDisplayPriceInclTax()) ?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>

    <?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
    <span class="price-excluding-tax" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <span class="cart-tax-total"
                  data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?= (int)$item->getId() ?>"}}'>
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
        <?= /* @noEscape */
        $customFormat->formatLong($block->getUnitDisplayPriceExclTax()) ?>
            </span>

        <?php if ($weeeHelper->getApplied($item)): ?>
            <span class="cart-tax-info no-display" id="eunit-item-tax-details<?= (int)$item->getId() ?>">
                <?php foreach ($weeeHelper->getApplied($item) as $tax): ?>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                        <?= /* @noEscape */
                        $customFormat->formatLong($tax['amount']) ?>
                    </span>
                <?php endforeach; ?>
            </span>
            <?php if ($block->displayFinalPrice()): ?>
                <span class="cart-tax-total"
                      data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?= (int)$item->getId() ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total')) ?>">
                        <?= /* @noEscape */
                        $customFormat->formatLong($block->getFinalUnitDisplayPriceExclTax()) ?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>
