<div class="row main-menu">
    <div class="col-md-9 col-12">
        <div class="row main-menu-items">
            <div class="col-md-3">
                <p><strong class="main-menu-title">Floral packaging</strong></p>
                <ul>
                    <li><a href="/en1/product.html">Sleeves</a></li>
                    <li><a href="#">Prefolds</a></li>
                    <li><a href="#">Sheets</a></li>
                    <li><a href="#">Fabrics &amp; Meshes</a></li>
                    <li><a href="#">Water Bouquets</a></li>
                    <li><a href="#">Tubes</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <p><strong class="main-menu-title">Potted packaging</strong></p>
                <ul>
                    <li><a href="#">Fastwraps</a></li>
                    <li><a href="#">Sheets</a></li>
                    <li><a href="#">EZ wraps</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <p><strong class="main-menu-title">Vases &amp; Containers</strong></p>
                <ul>
                    <li><a href="#">Glass Vases</a></li>
                    <li><a href="#">Wood Containers</a></li>
                    <li><a href="#">Tin Containers</a></li>
                    <li><a href="#">Ceramic Containers</a></li>
                    <li><a href="#">Woven Containers</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <p><strong class="main-menu-title">Bags &amp; Boxes</strong></p>
                <ul>
                    <li><a href="#">Short Bags</a></li>
                    <li><a href="#">Tall Bags</a></li>
                    <li><a href="#">Hat Boxes</a></li>
                </ul>
            </div>
        </div>
        <div class="row main-menu-items">
            <div class="col-md-3">
                <p><strong class="main-menu-title">Sustainable</strong></p>
                <ul>
                    <li><a href="#">FSC Kraft Paper</a></li>
                    <li><a href="#">PE</a></li>
                    <li><a href="#">Bio-LDPE</a></li>
                    <li><a href="#">PLA</a></li>
                    <li><a href="#">Glassine</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <p><strong class="main-menu-title">Picks</strong></p>
                <ul>
                    <li><a href="#">Stocks</a></li>
                    <li><a href="#">On-Demand</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <p><strong class="main-menu-title sale__label">SALE</strong></p>
                <ul>
                    <li><a href="#">Floral Packaging</a></li>
                    <li><a href="#">Potted Packaging</a></li>
                    <li><a href="#">Vases &amp; Containers</a></li>
                    <li><a href="#">Bags &amp; Boxes</a></li>
                    <li><a href="#">Picks</a></li>
                </ul>
            </div>
            <div class="col-md-3">&nbsp;</div>
        </div>
    </div>
    <div class="col-md-3 col-12">
        <div class="contet-banner-menu">
            <div class="content-bg">
                <h3>New Collection</h3>
                <a href="#">View products</a></div>
            <img src="{{media url=" wysiwyg/menu-image.png"}}" alt="Main menu" width="510" height="212">
        </div>
    </div>
</div>
