<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
/** @var \Amasty\Shopby\Block\Navigation\FilterRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */

$filterUniqId = $escaper->escapeHtml(uniqid());
$filterCode = $escaper->escapeHtml($filterSetting->getFilterCode());
?>

<?php if ($filterSetting->isShowSearchBox(count($filterItems))): ?>
    <?= /* @noEscape */
    $block->getSearchForm(); ?>
<?php endif; ?>

<form class="am-ranges"
      data-am-js="ranges"
      data-amshopby-filter="<?= $escaper->escapeHtmlAttr($filterCode); ?>"
      data-amshopby-filter-request-var="<?= $escaper->escapeHtmlAttr($block->getFilter()->getRequestVar()); ?>"
      autocomplete="off">
    <ol class="items am-filter-items-<?= /* @noEscape */
    $filterCode; ?>
        <?= /* @noEscape */
    $filterSetting->getEnableOverflowScroll() > 0 ? '-am-overflow' : '' ?>
        <?= /* @noEscape */
    $filterSetting->isMultiselect() ? '-am-multiselect' : '-am-singleselect' ?>"
        <?php if ($filterSetting->getEnableOverflowScroll() > 0): ?>
            style="max-height:<?= $escaper->escapeHtml($filterSetting->getEnableOverflowScroll()) ?>px;"
        <?php endif; ?>>
        <?php /** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */ ?>
        <?php foreach ($filterItems as $filterItem): ?>

            <?php if ($filterItem->getFilter()->getRequestVar() != 'custom'): ?>

                <?php $optionLabel = $filterItem->getOptionLabel(); ?>
                <?php $inputType = !$filterSetting->isMultiselect() ||
                in_array($filterCode, ['rating', 'stock']) ? 'radio' : 'checkbox' ?>
                <?php if ($filterItem->getValueString() == 1 || $filterItem->getValueString() == '1'): ?>
                    <li class="item <?= (!$filterItem->getCount()) ? '-empty-value' : '' ?>"
                        data-label="<?= /* @noEscape */
                        trim(preg_replace('/\s+/', ' ', $block->stripTags($optionLabel))) . ($filterCode == 'rating' ? __(' star(s)') : ''); ?>">
                        <?php if ($filterItem->getCount() >= 0): ?>
                            <?php $style = ($inputType == 'radio' && !$block->getRadioAllowed())
                            || in_array($filterCode, ['rating', 'stock']) ? 'display: none;' : ''; ?>
                            <a class="am-filter-item-<?= /* @noEscape */
                            $escaper->escapeHtmlAttr(uniqid()) ?>"
                               data-am-js="filter-item-default"
                               href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>"
                                <?= /* @noEscape */
                                $filterSetting->isAddNofollow() ? ' rel="nofollow"' : '' ?>>
                        <span class="label"><?= /* @noEscape */
                            $optionLabel; ?></span>
                            </a>
                            <input
                                name="amshopby[<?= /* @noEscape */
                                $block->getFilter()->getRequestVar(); ?>][]"
                                value="<?= $escaper->escapeHtmlAttr($filterItem->getValueString()); ?>"
                                type="<?= /* @noEscape */
                                $inputType; ?>"
                                style="<?= /* @noEscape */
                                $style ?>"
                                <?= /* @noEscape */
                                $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
                            />
                            <?php if ($inputType == 'checkbox'): ?>
                                <span class="amshopby-choice"></span>
                            <?php endif; ?>
                        <?php else: ?>
                            <span class="label"><?= /* @noEscape */
                                $optionLabel; ?></span>
                        <?php endif; ?>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach ?>
    </ol>
</form>
