<?php /** @var \Uzer\Samples\Block\Widget\Form $block */ ?>
<div class="samples-form-request">
    <div class="row">
        <div class="col-md-12 col-12">
            <h3><?= __('Request your free sample kit from The Floristshop') ?></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 info">
            <p>
                <?= __('Leave us a message and tell us the address where you want to receive your sample kit.') ?>
            </p>
            <p><?= __('All fields are required') ?><span class="field-required">*</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-12">
            <form action="<?= $block->getUrl('samples/kits/save') ?>" method="POST">
                <?= $block->getBlockHtml('formkey') ?>
                <div class="row">
                    <div class="col-md-6 col-12 from-group">
                        <label for="address_name"><?= __('Address Name') ?></label>
                        <input type="text" class="form-control" name="address_name" id="address_name" required>
                    </div>
                    <div class="col-md-6 col-12 from-group">
                        <label for="street_address"><?= __('Street Address') ?></label>
                        <input type="text" class="form-control" name="street_address" id="street_address" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-12 from-group">
                        <label for="country"><?= __('Country') ?></label>
                        <input type="text" class="form-control" name="country" id="country" required>
                    </div>
                    <div class="col-md-6 col-12 from-group">
                        <label for="state"><?= __('State') ?></label>
                        <input type="text" class="form-control" name="state" id="state" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-12 from-group">
                        <label for="city"><?= __('City') ?></label>
                        <input type="text" class="form-control" name="city" id="city" required>
                    </div>
                    <div class="col-md-6 col-12 from-group">
                        <label for="zip_code"><?= __('Zip Code') ?></label>
                        <input type="text" class="form-control" name="zip_code" id="zip_code" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-12 from-group">
                        <label for="message"><?= __('Message') ?></label>
                        <textarea name="message" id="message" class="form-control" required cols="30"
                                  rows="10"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-12 submit-button-container align-content-center">
                        <p>
                            <button type="submit" class="btn decowraps-button btn-request-sample">
                                <?= __('Send Kit Request') ?>
                            </button>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
