<?php /** @var \Uzer\Samples\Block\Email\Items $block */ ?>

<?php $items = $block->getItems(); ?>

<table width="100%" cellspacing="0" cellpadding="0">
    <tbody>
    <tr>
        <td style="border-bottom: 1px solid #DFDFDF;padding-bottom: 10px;"><span
                style="font-size: 14px;font-weight: 600;text-align:left;display: block;"><?= __('Article') ?></span>
        </td>
        <td style="border-bottom: 1px solid #DFDFDF;padding-bottom: 10px;">&nbsp;</td>
        <td colspan="2" style="border-bottom: 1px solid #DFDFDF;padding-bottom: 10px;"><span
                style="font-size: 14px;font-weight: 600;text-align:right;display: block;"><?= __('Qty Units') ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="4" style="padding: 20px 0;border-bottom: 1px solid #E7E7E7;">
            <table width="100%" cellspacing="0" cellpadding="0">
                <tbody>
                <?php foreach ($items as $item): ?>
                    <?php if ($item->getIsParent() || is_null($item->getParent())): ?>
                        <?php $children = $item->getChildren() ?>
                        <tr>
                            <td>
                                <span
                                    style="font-size: 16px;font-weight: 600;text-align:left;display: block;line-height: 30px;display: block;"><?= $item->getName() ?></span>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        <?php if (count($children) > 0): ?>

                            <?php foreach ($children as $child): ?>
                                <?php $attribute = $block->getProduct($child->getProductId());
                                $multiple_attributes = $attribute->getResource()->getAttribute('material')->getFrontend()->getValue($attribute);
                                ?>
                                <tr>
                                    <td colspan="2"><span
                                            style="font-size: 14px;font-weight: 400;text-align:left;line-height: 30px;display: block;">Ref: <?= $child->getSku() ?>
                                            <?php if ($attribute->getAttributeText('size')): ?> | <?= $attribute->getAttributeText('size'); ?><?php endif; ?>
                                            <?php if ($attribute->getAttributeText('color')): ?> | <?= $attribute->getAttributeText('color'); ?><?php endif; ?></span>
                                    </td>
                                    <td width="20"><span
                                            style="font-size: 14px;font-weight: 400;text-align:right;display: block; width:100px;"><?= $child->getQty(); ?></span>
                                    </td>
                                </tr>

                            <?php endforeach; ?>

                        <?php elseif (is_null($item->getParent())): ?>


                            <?php $attribute_simple = $block->getProduct($item->getProductId());
                            $multiple_attributes_simple = $attribute_simple->getResource()->getAttribute('material')->getFrontend()->getValue($attribute_simple);
                            ?>

                            <tr>
                                <td colspan="2"><span
                                        style="font-size: 14px;font-weight: 400;text-align:left;line-height: 30px;display: block;">Ref: <?= $attribute_simple->getSku() ?><?php if ($attribute_simple->getAttributeText('size')): ?> |
                                            <?= $attribute_simple->getAttributeText('size'); ?>
                                        <?php endif; ?><?php if ($attribute_simple->getAttributeText('color')): ?> | <?= $attribute_simple->getAttributeText('color'); ?><?php endif; ?></span>
                                </td>
                                <td width="20"><span
                                        style="font-size: 14px;font-weight: 400;text-align:right;display: block; width:100px;"><?= $item->getQty(); ?></span>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td style="padding: 15px 0px 5px 0;display: block;"><span
                style="font-size: 14px;font-weight: 400;text-align:right;display: block;line-height: 30px;display: block;"><?= __('Subtotal products:') ?></span>
        </td>
        <td style="padding: 15px 0px 5px 0;width: 10%;"><span
                style="font-size: 14px;font-weight: 400;text-align:right;display: block;line-height: 30px;display: block;"><?= $block->getCurrencySymbol() ?>0.00</span>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td style="padding: 0px 0px 5px 0;display: block;"><span
                style="font-size: 14px;font-weight: 400;text-align:right;display: block;line-height: 30px;display: block;"><?= __('Delivery:') ?></span>
        </td>
        <td style="padding: 0px 0px 5px 0;width: 10%;"><span
                style="font-size: 14px;font-weight: 400;text-align:right;display: block;line-height: 30px;display: block;"><?= $block->getCurrencySymbol() ?>0.00</span>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td style="padding: 0px 0px 5px 0;display: block;"><span
                style="font-size: 14px;font-weight: 400;text-align:right;display: block;line-height: 30px;display: block;"><?= __('TAX % / VAT %:') ?></span>
        </td>
        <td style="padding: 0px 0px 5px 0;width: 10%;"><span
                style="font-size: 14px;font-weight: 400;text-align:right;display: block;line-height: 30px;display: block;"><?= $block->getCurrencySymbol() ?>0.00</span>
        </td>
    </tr>
    </tbody>
</table>
