<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<img src="https://decowraps.com/static/frontend/bs_gota/bs_gota_home_3/en_US/css/images/ico-logout.svg" class="logout-logo" alt="You Are Signed Ou">
<h1 class="signed-out"><?= $block->escapeHtml(__('You Are Signed Out')) ?></h1>
<p><?= $block->escapeHtml(__('You have signed out and will go to our homepage in 5 seconds.')) ?></p>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/logout-redirect": {
                "url": "<?= $block->escapeJs($block->escapeUrl($block->getUrl())) ?>"
            }
        }
    }
</script>
