<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct();
$config_point2 = $this->helper('Rokanthemes\RokanBase\Helper\Data')->getConfigData('setting_categories/categories/point2');
$arr_config_point2 = explode(',', $config_point2);
$qty = 1;
$categories = $_product->getCategoryIds();
if (count($categories) > 0 && count($arr_config_point2) > 0) {
    foreach ($arr_config_point2 as $val1) {
        if (in_array(trim($val1), $categories)) {
            $qty = 3;
            break;
        }
    }
}
?>
<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart-uzer">
        <div>
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="row box-tocart-headers">
                    <div class="col-md-4">
                        <span><?= __('Boxes') ?></span>
                    </div>
                    <div class="col-md-4">
                        <span><?= __('Units') ?></span>
                    </div>
                    <div class="col-md-4">
                        <span><?= __('Subtotal') ?></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="field qty">
                            <div class="row">
                                <div class="col-md-3 qty-editor">
                                    <a class="qty-down-fixed-onclick boxes-down" href="#"><span
                                            class="icon-chevron-left"></span></a>
                                </div>
                                <div class="col-md-6 qty-number">
                                    <div class="control">
                                        <input type="number"
                                               name="boxes"
                                               id="boxes"
                                               maxlength="12"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Quantity') ?>" class="input-text qty"
                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                        />
                                        <input type="hidden"
                                               name="qty"
                                               id="qty"
                                               maxlength="12"
                                               value="<?php /* @escapeNotVerified */
                                               echo $qty * 1 ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Quantity') ?>" class="input-text qty"
                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                        />
                                    </div>
                                </div>
                                <div class="col-md-3 qty-editor">
                                    <a class="qty-up-fixed-onclick boxes-up" href="#"><span
                                            class="icon-chevron-right"></span></a>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-4">
                        <span class="total-units">0</span>
                    </div>
                    <div class="col-md-4">
                        <span class="total-subtotal">$0</span>
                    </div>
                </div>
            <?php endif; ?>
            <div class="row">
                <div class="col-12">
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
