<?php
use Magento\Framework\App\ObjectManager;
use Uzer\Checkoutstep\Model\CustomFormat;

/**
 * Copyright © Magento, Inc.
 * All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
/** @var CustomFormat $customFormat */
$customFomat = ObjectManager::getInstance()->create(CustomFormat::class);
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
<div class="orders-history-title-container">
	<div class="orders-history-title">
		<h2><?= $block->escapeHtml(__('Online Orders')) ?></h2>
	</div>
	<div class="orders-history-paginator">
		<div class="orders-history-counter">
    <?php $count = count($this->getOrders()); ?>
    <?php if ($count > 1) : ?>
    <?= $block->escapeHtml("".$count." Orders") ?>
    <?php else : ?>
    <?= $block->escapeHtml("".$count." Order") ?>
    <?php endif ?>
    </div>
<?php if ($block->getPagerHtml()) : ?>
        <div class="orders-history-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
    </div>
</div>
<div class="table-wrapper orders-history">
	<table class="data table table-order-items history"
		id="my-orders-table">
		<caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
		<thead>
			<tr>
				<th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
				<th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col name"><?= $block->escapeHtml(__('Contact Name')) ?></th>
				<th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total Listing')) ?></th>
				<th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
				<th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
			</tr>
		</thead>
		<tbody>
            	<?php /** @var \Magento\Sales\Model\Order $_order */ ?>
                <?php foreach ($_orders as $_order) : ?>
                    <tr>
				<td data-th="<?= $block->escapeHtml(__('Order #')) ?>"
					class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
				<td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                         <td
					data-th="<?= $block->escapeHtml(__('Contact Name')) ?>"
					class="col name"><?= $block->escapeHtml($_order->getShippingAddress()->getFirstname()) ?> <?= $block->escapeHtml($_order->getShippingAddress()->getLastname()) ?></td>
				<td data-th="<?= $block->escapeHtml(__('Order Total Listing')) ?>"
					class="col total"><?= /* @noEscape */$customFomat->format($_order->getGrandTotal()) ?></td>
				<td data-th="<?= $block->escapeHtml(__('Status')) ?>"
					class="col status"><span
					class="<?= $block->escapeHtml($_order->getStatus()) ?>"><?= $block->escapeHtml($_order->getStatusLabel()) ?></span></td>
				<td data-th="<?= $block->escapeHtml(__('Actions')) ?>"
					class="col actions"><a
					href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>"
					class="action view"> <span><?= $block->escapeHtml(__('View')) ?></span>
				</a></td>
			</tr>
                <?php endforeach; ?>
            </tbody>
	</table>
</div>
<?php else : ?>
<div class="message info empty">
	<span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span>
</div>
<?php endif ?>
<?php if ($block->getPagerHtml()) : ?>
<div class="orders-history-paginator toolbar bottom"><?= $block->getPagerHtml() ?></div>
<?php endif ?>

