<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $buttonTitle = __('Update cart'); ?>
<div class="col-md-6 col-6">
    <div class="actions">
        <button type="button"
                title="<?php /* @escapeNotVerified */
                echo $buttonTitle ?>"
                class="action primary tocart"
                id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */
                        echo $buttonTitle ?></span>
        </button>
    </div>
</div>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    let widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });
                    widget.catalogAddToCart('submitForm', $(form));
                    return false;
                }
            });
            $('.tocart').click(function () {
                $('#product_addtocart_form').mage('validation', {
                    radioCheckboxClosest: '.nested',
                    submitHandler: function (form) {
                        let widget = $(form).catalogAddToCart({
                            bindSubmit: false
                        });
                        widget.catalogAddToCart('submitForm', $(form));
                        return false;
                    }
                });
            });
        });
    </script>
<?php endif; ?>
