<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Uzer\Catalog\Block\Cart\Item\Renderer\Actions\Actions */
?>
<a href="#"
   title="<?= $block->escapeHtml(__('Delete')) ?>"
   class="action action-delete" data-delete='<?= /* @noEscape */
$block->getDeletePostJson() ?>' data-wishlist='<?= /* @noEscape */
$block->getMoveFromCartParams() ?>'>
    <span>
        <?= $block->escapeHtml(__('Delete')) ?>
    </span>
</a>
