<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */


// @codingStandardsIgnoreFile

?>
<div class="block-newsletter-form">
    <div class="block newsletter newsletter-form">
        <img class="newsletter-icon" src="/media/icons/newsletter-icon.svg" alt="newsletter-icon">
        <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
        ?>
        <h2>
            <?php
            $conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')
                ->getValue('themeoption/newsletter_form/title_content_form', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $storeManager->getStore()->getId());
            echo $conf;
            ?>
            <?php echo $block->getConfig('title_content_form', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $storeManager->getStore()->getId()); ?></h2>
        <div class="newsletter-des">
            <?php
            $conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')
                ->getValue('themeoption/newsletter_form/content_form', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $storeManager->getStore()->getId());
            echo $conf;
            ?>
            <?php echo $block->getConfig('title_content_form', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $storeManager->getStore()->getId()); ?>
        </div>

        <div class="content">
            <form class="form subscribe" novalidate action="<?php /* @escapeNotVerified */
            echo $block->getFormActionUrl() ?>" method="post"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">
                <div class="field newsletter">
                    <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */
                            echo __('Sign Up for Our Newsletter:') ?></span></label>
                    <div class="control">
                        <input name="email" type="email" id="newsletter" placeholder="<?php /* @escapeNotVerified */
                        echo __('Your email address') ?>" data-validate="{required:true, 'validate-email':true}"/>
                        <div class="actions">
                            <button class="action subscribe primary" title="<?php /* @escapeNotVerified */
                            echo __('Subscribe') ?>" type="submit">
                                <span><?php /* @escapeNotVerified */
                                    echo __('Subscribe') ?></span>
                            </button>
                        </div>
                    </div>
                    <p class="newsletter-privacy-policy">By subscribing I accept Decowraps' <a
                            href="<?= $block->getUrl('privacy-policy-cookie-restriction-mode') ?>">Privacy
                            policy </a></p>
                </div>

            </form>
        </div>
    </div>

</div>
