<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <h2 id="block-customer-login-heading" role="heading"
            aria-level="2"><?= $block->escapeHtml(__('Customer Information')) ?></h2>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div
                    class="field note"><?= $block->escapeHtml(__('If you already have an account, please log in.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               id="email" type="email" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email Address ')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               placeholder="<?= $block->escapeHtmlAttr(__('Your email')) ?>"
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass"
                               title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('Your password')) ?>"
                               data-validate="{required:true}">
                                <div class="password__toggle">
                                    <a id="password__toggle" href="#" class="enable" onClick="viewPassword()"></a>
                                </div>						
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="row">
                        <div class="col-md-4 col-6">
                            <label for="remember">
                                <input type="checkbox" class="remember" id="remember">
                                <?= $block->escapeHtml(__('Stay logged in')) ?>
                            </label>
                        </div>
                        <div class="col-md-5 col-6 remind__pass">
                            <div class="secondary">
                                <a class="action remind"
                                   href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
                                    <span>
                                         <?= $block->escapeHtml(__('Forgot Your Password?')) ?>
                                    </span></a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-12">
                            <div class="buttons">
                                <div class="primary">
                                    <button type="submit" class="action login primary" name="send" id="send2">
                                        <span><?= $block->escapeHtml(__('Login')) ?></span></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form"
                }
            }
        }

    </script>
</div>
