<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Helper\Address;

/** @var \Magento\Customer\Block\Form\Register $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $block->getData('addressHelper');
/** @var \Magento\Directory\Helper\Data $directoryHelper */
$directoryHelper = $block->getData('directoryHelper');
$formData = $block->getFormData();
?>
<?php $displayAll = $block->getConfig('general/region/display_all'); ?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<div class="custom-register-block">
    <div class="row">
        <div class="col-md-12 col-12">
            <p><?= __('Thank you for your interest in opening an account with Decowraps. Partnering with Decowraps has many benefits:') ?></p>
        </div>
    </div>
    <div class="row">
        <div class="container-highlights-register col-md-12 col-12">
            <div class="row">
                <div class="col-md-4 col-12 d-flex">
                    <div class="content-customer">
                        <img src="<?php echo $this->getViewFileUrl('Magento_Customer::images/wishlist.svg'); ?>"/>
                        <strong><?= __('Custom Wishlist') ?></strong>
                    </div>
                </div>
                <div class="col-md-5 col-12 d-flex">
                    <div class="content-customer">
                        <img
                            src="<?php echo $this->getViewFileUrl('Magento_Customer::images/customer-service.svg'); ?>"/>
                        <strong><?= __('Personalized Customer Service') ?></strong>
                    </div>
                </div>
                <div class="col-md-3 col-12 d-flex">
                    <div class="content-customer">
                        <img src="<?php echo $this->getViewFileUrl('Magento_Customer::images/samples.svg'); ?>"/>
                        <strong><?= __('Free Samples') ?></strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<form class="form create account form-create-account"
      action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= /* @noEscape */
    $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset create info">
        <legend class="legend-title"><span><?= $escaper->escapeHtml(__('Customer Information')) ?></span></legend>
        <legend class="legend-fields"><span><?= $escaper->escapeHtml(__('All fields are required*')) ?></span></legend>
        <br>
        <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getLayout()
            ->createBlock(\Magento\Customer\Block\Widget\Name::class)
            ->setObject($formData)
            ->setForceUseCustomerAttributes(true)
            ->toHtml() ?>
        <div class="row">
            <div class="col-md-6 col-12">
                <div class="field company required">
                    <label class="label" for="company">
                        <span><?= $escaper->escapeHtml(__('Company')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               id="company"
                               name="company"
                               value="<?= $escaper->escapeHtmlAttr($formData->getCompany()) ?>"
                               title="<?= $escaper->escapeHtmlAttr(__('Company')) ?>"
                               class="input-text required-entry"
                               data-validate="{required:true, 'validate-length':true}"
                               maxlength="100">
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-12">
                <div class="field title">
                    <label class="label"
                           for="title"><span><?= __('Title') ?></span></label>
                    <div class="control">
                        <input type="text" id="title"
                               name="title"
                               value=""
                               maxlength="100"
                               title="<?= __('Title') ?>"
                               class="input-text" data-validate="{maxlength:15}">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-12">
                <div class="field field-name-phone required">
                    <label class="label"
                           for="title"><span><?= __('Phone Number') ?></span></label>
                    <div class="control">
                        <input type="text" id="phone"
                               name="phone"
                               value=""
                               maxlength="100"
                               title="<?= __('Phone Number') ?>"
                               class="input-text title"
                               data-validate='{"required": true,"minlength": 7,"maxlength": 13}'>
                    </div>
                </div>
            </div>
        </div>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($formData->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($formData->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($formData->getGender())->toHtml() ?>
        <?php endif ?>
        <?= $block->getChildHtml('fieldset_create_info_additional') ?>
    </fieldset>
    <?php if ($block->getShowAddressFields()): ?>
        <?php $cityValidationClass = $addressHelper->getAttributeValidationClass('city'); ?>
        <?php $postcodeValidationClass = $addressHelper->getAttributeValidationClass('postcode'); ?>
        <?php $regionValidationClass = $addressHelper->getAttributeValidationClass('region'); ?>
        <fieldset class="fieldset address">
            <legend class="legend"><span><?= $escaper->escapeHtml(__('Address Information')) ?></span></legend>
            <br>
            <input type="hidden" name="create_address" value="1"/>

            <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
            <?php if ($_company->isEnabled()): ?>
                <?= $_company->setCompany($formData->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
            <?php if ($_telephone->isEnabled()): ?>
                <?= $_telephone->setTelephone($formData->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
            <?php if ($_fax->isEnabled()): ?>
                <?= $_fax->setFax($formData->getFax())->toHtml() ?>
            <?php endif ?>

            <?php
            $_streetValidationClass = $addressHelper->getAttributeValidationClass('street');
            ?>

            <div class="field street required">
                <label for="street_1" class="label">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('street') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="street[]"
                           value="<?= $escaper->escapeHtmlAttr($formData->getStreet(0)) ?>"
                           title="<?= /* @noEscape */
                           $block->getAttributeData()->getFrontendLabel('street') ?>"
                           id="street_1"
                           maxlength="100"
                           class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>">
                    <div class="nested">
                        <?php
                        $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass));
                        $streetLines = $addressHelper->getStreetLines();
                        ?>
                        <?php for ($_i = 2, $_n = $streetLines; $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */
                                $_i ?>">
                                    <span><?= $escaper->escapeHtml(__('Address')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text"
                                           name="street[]"
                                           value="<?= $escaper->escapeHtml($formData->getStreetLine($_i - 1)) ?>"
                                           title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i)) ?>"
                                           id="street_<?= /* @noEscape */
                                           $_i ?>"
                                           maxlength="100"
                                           class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
                </label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('region') ?></span>
                </label>
                <div class="control">
                    <select id="region_id"
                            name="region_id"
                            title="<?= /* @noEscape */
                            $block->getAttributeData()->getFrontendLabel('region') ?>"
                            class="validate-select region_id">
                        <option value="">
                            <?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?>
                        </option>
                    </select>
                    <?= /* @noEscape */
                    $secureRenderer->renderStyleAsTag("display: none;", 'select#region_id') ?>
                    <input type="text"
                           id="region"
                           maxlength="100"
                           name="region"
                           value="<?= $escaper->escapeHtml($block->getRegion()) ?>"
                           title="<?= /* @noEscape */
                           $block->getAttributeData()->getFrontendLabel('region') ?>"
                           class="input-text <?= $escaper->escapeHtmlAttr($regionValidationClass) ?>">
                    <?= /* @noEscape */
                    $secureRenderer->renderStyleAsTag("display: none;", 'input#region') ?>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('city') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="city"
                           maxlength="100"
                           value="<?= $escaper->escapeHtmlAttr($formData->getCity()) ?>"
                           title="<?= /* @noEscape */
                           $block->getAttributeData()->getFrontendLabel('city') ?>"
                           class="input-text <?= $escaper->escapeHtmlAttr($cityValidationClass) ?>"
                           id="city">
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="postcode"
                           maxlength="100"
                           value="<?= $escaper->escapeHtmlAttr($formData->getPostcode()) ?>"
                           title="<?= /* @noEscape */
                           $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                           id="zip"
                           class="input-text validate-zip-international
                            <?= $escaper->escapeHtmlAttr($postcodeValidationClass) ?>">
                </div>
            </div>

            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif; ?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>
    <fieldset class="fieldset create account"
              data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Create a Log In')) ?></span></legend>
        <br>
        <div class="row">
            <div class="col-md-6 col-12">
                <div class="field required">
                    <label for="email_address"
                           class="label"><span><?= $escaper->escapeHtml(__('Email Address')) ?></span></label>
                    <div class="control">
                        <input type="email"
                               name="email"
                               maxlength="100"
                               autocomplete="email"
                               id="email_address"
                               value="<?= $escaper->escapeHtmlAttr($formData->getEmail()) ?>"
                               title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                               class="input-text"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
            </div>
        </div>

        <div class="row password-container">
            <div class="col-md-6 col-12">
                <div class="field password required">
                    <label for="password" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input type="password" name="password" id="password"
                               title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                               class="input-text"
                               data-password-min-length="<?=
                               $escaper->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                               data-password-min-character-sets="<?=
                               $escaper->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                               data-validate="{required:true, 'validate-customer-password':true,maxlength:50}"
                               autocomplete="off"
                               maxlength="50">
                        <div class="password__toggle">
                            <a id="registerPassword__toggle" class="enable" onClick="registerPassword()"></a>
                        </div>
                        <div id="password-strength-meter-container" data-role="password-strength-meter"
                             aria-live="polite">
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?= $escaper->escapeHtml(__('Password Strength')) ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $escaper->escapeHtml(__('No Password')) ?>
                        </span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-md-6 col-12">
                <div class="field confirmation required">
                    <label for="password-confirmation" class="label">
                        <span><?= $escaper->escapeHtml(__('Confirm Password')) ?></span>
                    </label>
                    <div class="control">
                        <input type="password"
                               name="password_confirmation"
                               title="<?= $escaper->escapeHtmlAttr(__('Confirm Password')) ?>"
                               id="password-confirmation"
                               class="input-text"
                               data-validate="{required:true,equalTo:'#password,maxlength:50'}"
                               autocomplete="off"
                               maxlength="50">
                        <div class="password__toggle">
                            <a id="registerCPassword__toggle" class="enable" onClick="registerCPassword()"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="col-md-12 col-6 terms-conditions required">
        <label for="terms">
            <span class="control">
                <input type="checkbox" name="terms"
                       required
                       value="1"
                       id="terms"
                       data-validate="{required:true,'required-entry':true}"> <?= __('I agree to Decowraps.com <a href="%1" target="_blank">Terms and Conditions</a> and <a href="%2" target="_blank">Privacy Policy</a>', $block->getUrl('terms-of-service'), $block->getUrl('privacy-policy-cookie-restriction-mode')) ?>
            </span>
        </label>
    </div>

    <fieldset class="fieldset additional_info">
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="row">
            <div class="col-md-6 col-12">
                <div class="secondary">
                    <a class="action back"
                       href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                        <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-12">
                <div class="primary">
                    <button type="submit"
                            class="action submit btn-decowraps"
                            title="<?= $escaper->escapeHtmlAttr(__('Create an Account')) ?>">
                        <span><?= $escaper->escapeHtml(__('Create an Account')) ?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
<?php $ignore = /* @noEscape */
    $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = {$ignore};

    dataForm.mage('validation', {
script;
if ($_dob->isEnabled()):
    $scriptString .= <<<script
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
    }).find('input:text').attr('autocomplete', 'off');
});
script;
?>
<?= /* @noEscape */
$secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php if ($block->getShowAddressFields()): ?>
    <?php
    $regionJson = /* @noEscape */
        $directoryHelper->getRegionJson();
    $regionId = (int)$formData->getRegionId();
    $countriesWithOptionalZip = /* @noEscape */
        $directoryHelper->getCountriesWithOptionalZip(true);
    ?>
    <script type="text/x-magento-init">
        {
            "#country": {
                "regionUpdater": {
                    "optionalRegionAllowed": <?= /* @noEscape */
        $displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": {$regionJson},
                "defaultRegion": "{$regionId}",
                "countriesWithOptionalZip": {$countriesWithOptionalZip}
            }
        }
    }

    </script>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery'], function ($) {
        'use strict';

        $(document).ready(function () {
            $('#form-validate').on('submit', function (e) {
                let companyField = $('#company');
                let companyValue = companyField.val().trim();

                if (companyValue === '' || companyValue.length > 100) {
                    e.preventDefault();
                    e.stopPropagation();

                    $('.mage-error').remove();

                    if (companyValue === '') {
                        companyField.addClass('mage-error');
                        companyField.after('<div for="company" generated="true" class="mage-error" id="company-error"><?= $escaper->escapeJs(__('This is a required field.'))?></div>');
                    }

                    $('html, body').animate({
                        scrollTop: companyField.offset().top - 50
                    }, 500);

                    return false;
                }

                return true;
            });
        });
    });
</script>
<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        },
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            },
            "Magento_Ui/js/core/app": {
                "components": {
                    "showPassword": {
                        "component": "Magento_Customer/js/show-password",
                        "passwordSelector": "#password,#password-confirmation"
                    }
                }
            }
        }
    }
</script>
